version: '3'

services:
  # テスト用の環境
  node:
    image: node:12.18.3-alpine3.12
    volumes:
      - ./:/project:delegated
    tty: true
    working_dir: /project
    environment:
      # AWS-SDKを動作させるために、必要な変数
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: dummy
    networks:
      default:

  # s3mock
  s3:
    image: adobe/s3mock
    environment:
      - initialBuckets=test-backet
    ports:
      -  "22011:22"
    networks:
      default:
        aliases:
          - s3mock.test.com
networks:
  default:
